// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Safety_Tech.Models.Models;

#nullable disable

namespace Safety_Tech.Models.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20250925140925_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Safety_Tech.Models.Models.PayPeriod", b =>
                {
                    b.Property<int>("PayPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayPeriodId"));

                    b.Property<int>("PayPeriodEndDay")
                        .HasColumnType("int");

                    b.Property<int>("PayPeriodStartDay")
                        .HasColumnType("int");

                    b.HasKey("PayPeriodId");

                    b.ToTable("PayPeriod", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex(new[] { "UserId" }, "IX_Payment_UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusType")
                        .HasColumnType("int");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex(new[] { "ManagerId" }, "IX_PaymentStatuses_ManagerId");

                    b.HasIndex(new[] { "PaymentId" }, "IX_PaymentStatuses_PaymentId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_PaymentStatuses_ProjectId");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.ProjectTeam", b =>
                {
                    b.Property<int>("ProjectTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTeamId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("ProjectTeamId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_ProjectTeam_ProjectId");

                    b.ToTable("ProjectTeam", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.WorkTimeEntry", b =>
                {
                    b.Property<int>("WorkTimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkTimeEntryId"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("WorkingHours")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("WorkTimeEntryId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_WorkTimeEntries_ProjectId");

                    b.HasIndex(new[] { "UserId" }, "IX_WorkTimeEntries_UserId");

                    b.HasIndex(new[] { "WorkTypeId" }, "IX_WorkTimeEntries_WorkTypeId");

                    b.ToTable("WorkTimeEntries");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.WorkType", b =>
                {
                    b.Property<int>("WorkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkTypeId"));

                    b.Property<decimal>("WorkTypeHours")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("WorkTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTypeSign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkTypeId");

                    b.ToTable("WorkType", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRole_RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.Payment", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.PaymentStatus", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.User", "Manager")
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("ManagerId");

                    b.HasOne("Safety_Tech.Models.Models.Payment", "Payment")
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safety_Tech.Models.Models.Project", "Project")
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Manager");

                    b.Navigation("Payment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.ProjectTeam", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.Project", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.RefreshToken", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safety_Tech.Models.Models.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.UserRole", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safety_Tech.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.WorkTimeEntry", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.Project", "Project")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safety_Tech.Models.Models.User", "User")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Safety_Tech.Models.Models.WorkType", "WorkType")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("Safety_Tech.Models.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safety_Tech.Models.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.Payment", b =>
                {
                    b.Navigation("PaymentStatuses");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.Project", b =>
                {
                    b.Navigation("PaymentStatuses");

                    b.Navigation("ProjectTeams");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.User", b =>
                {
                    b.Navigation("PaymentStatuses");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("Safety_Tech.Models.Models.WorkType", b =>
                {
                    b.Navigation("WorkTimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
